### ISSUE TITLE
Replace &nbsp with margins/padding

### ISSUE THREAD

**Issue by strizzwald** [FRossouw/Web-Assignment-01#3]
https://github.com/FRossouw/Web-Assignment-01/blob/7f57cc8417b099eb85e5536b8171bfb089d9627d/index.html#L187-L189

In-place of `&nbsp&nbsp&nbsp`.... you could use  the `<span>` tag this way

`<span class="year">Third year</span><span>: Year average : 70.5%</span>`

```css
.year {
  margin-right: 5px; /*or some desired spacing value */
}
````
